# Generated by Django 4.2.15 on 2024-08-23 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bye', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='genre',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
